[package]
name = "hello_rust"
version = "0.1.0"
authors = ["yuliyu123 <15375154510@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = "1.21.0"
chrono = "0.4.22"